BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
SET client_min_messages TO WARNING;

CREATE TABLE role (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    code VARCHAR(20) UNIQUE,
    primary key (id)
);

CREATE TABLE languages (
    code VARCHAR(5) PRIMARY KEY, -- 'en', 'kk', 'ru'
    name TEXT NOT NULL,
    display_order INT
);

CREATE TABLE grade_levels (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL, -- Fallback name
    display_order INT NOT NULL,
    icon_url TEXT,
    background_color VARCHAR(7),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Переводы для названий уровней классов
CREATE TABLE grade_level_translations (
    grade_level_id BIGINT NOT NULL REFERENCES grade_levels(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    name TEXT NOT NULL, -- 'Класс 2', 'Grade 2', '2-сынып'
    PRIMARY KEY (grade_level_id, language_code)
);

-- Основные сущности
CREATE TABLE "user" (
    id BIGSERIAL PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT, -- Может быть NULL для пользователей вошедших через OAuth
    avatar_url TEXT,
    role_id bigint REFERENCES role(id),
    experience_points BIGINT NOT NULL DEFAULT 0,
    is_new_user BOOLEAN NOT NULL DEFAULT TRUE,
    preferred_language_code VARCHAR(5) REFERENCES languages(code),
    settings JSONB, -- Тут хронятся настройки пользователя типо там звук, уведомления и т.п.
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at TIMESTAMPTZ
);

-- Таблица для учебных классов создаваемых учителями
CREATE TABLE classrooms (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(8) NOT NULL UNIQUE, -- Уникальный 6-8 значный код для присоединения студентов
    name TEXT NOT NULL,
    grade_level_id BIGINT NOT NULL REFERENCES grade_levels(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE, -- Класс можно заархивировать, или временно закрыть тут как сам решишиь
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Таблицы-связки

-- Связывает учителей с классами
CREATE TABLE teacher_classrooms (
    id BIGSERIAL PRIMARY KEY,
    teacher_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
    is_primary_teacher BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ, -- Храним историю, не удаляя запись физически
    UNIQUE (teacher_id, classroom_id)
);

-- Связывает студентов с классами
CREATE TABLE student_classrooms (
    id BIGSERIAL PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ, -- Храним историю, не удаляя запись физически
    UNIQUE (student_id, classroom_id)
);

-- Учебные материалы

-- Главы учебного материала сгруппированные по уровню обучения (grade)
CREATE TABLE chapters (
    id BIGSERIAL PRIMARY KEY,
    grade_level_id BIGINT NOT NULL REFERENCES grade_levels(id),
    icon_url TEXT,
    icon_blur_hash TEXT,
    chapter_order INT NOT NULL, -- Определяет порядок глав внутри одного grade_level
    color_scheme TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (grade_level_id, chapter_order)
);

-- Переводы для названий и имен глав на разные языки
CREATE TABLE chapter_translations (
    chapter_id BIGINT NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    title TEXT NOT NULL, -- 'Глава 1', 'Chapter 1'
    name TEXT NOT NULL,  -- 'Мир вокруг нас', 'The World Around Us'
    PRIMARY KEY (chapter_id, language_code)
);

-- Уроки внутри глав
CREATE TABLE lessons (
    id BIGSERIAL PRIMARY KEY,
    chapter_id BIGINT NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
    thumbnail_url TEXT,
    thumbnail_blur_hash TEXT,
    lesson_order INT NOT NULL, -- Определяет порядок уроков внутри одной главы
    background_color TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (chapter_id, lesson_order)
);

-- Переводы для названий уроков
CREATE TABLE lesson_translations (
    lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    title TEXT NOT NULL,
    PRIMARY KEY (lesson_id, language_code)
);

-- Активности (мини-игры) внутри уроков
CREATE TABLE activities (
    id BIGSERIAL PRIMARY KEY,
    lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    activity_type TEXT NOT NULL, -- 'Quiz', 'Memory', 'Sorting', 'Reorder', 'Matching', 'FillTheBlank', 'Snapshot', 'Image Boom', 'Mastery'
    icon_url TEXT,
    icon_blur_hash TEXT,
    activity_order INT NOT NULL, -- Определяет порядок активностей внутри одного урока
    background_color TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (lesson_id, activity_order)
);

-- Переводы для названий и подсказок (промптов) активностей.
CREATE TABLE activity_translations (
    activity_id BIGINT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    title TEXT NOT NULL, -- 'Сортировка', 'Sorting'
    prompt TEXT NOT NULL, -- 'Распределите предметы по категориям'
    PRIMARY KEY (activity_id, language_code)
);

-- Контент мини-игр

-- Элементы для игры "Memory"
CREATE TABLE memory_game_items (
    id BIGSERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    has_image BOOLEAN NOT NULL DEFAULT FALSE,
    image_url TEXT,
    image_blur_hash TEXT,
    item_order INT NOT NULL
);

CREATE TABLE memory_game_item_translations (
    item_id BIGINT NOT NULL REFERENCES memory_game_items(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    item_name TEXT NOT NULL,
    PRIMARY KEY (item_id, language_code)
);

-- Вопросы для игры "Quiz"
CREATE TABLE quiz_questions (
    id BIGSERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    question_order INT NOT NULL
);

CREATE TABLE quiz_question_translations (
    question_id BIGINT NOT NULL REFERENCES quiz_questions(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    question_text TEXT NOT NULL,
    PRIMARY KEY (question_id, language_code)
);

-- Варианты ответов для вопросов в "Quiz"
CREATE TABLE quiz_answer_options (
    id BIGSERIAL PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES quiz_questions(id) ON DELETE CASCADE,
    is_correct BOOLEAN NOT NULL,
    option_order INT NOT NULL
);

CREATE TABLE quiz_answer_option_translations (
    option_id BIGINT NOT NULL REFERENCES quiz_answer_options(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    answer_text TEXT NOT NULL,
    PRIMARY KEY (option_id, language_code)
);

-- Категории для игры "Sorting" (и "Reorder")
CREATE TABLE sorting_categories (
    id BIGSERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    category_order INT NOT NULL
);

CREATE TABLE sorting_category_translations (
    category_id BIGINT NOT NULL REFERENCES sorting_categories(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    name TEXT NOT NULL,
    PRIMARY KEY (category_id, language_code)
);

-- Элементы для игры "Sorting" (и "Reorder")
CREATE TABLE sorting_items (
    id BIGSERIAL PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES sorting_categories(id) ON DELETE CASCADE,
    image_url TEXT,
    image_blur_hash TEXT,
    item_order INT NOT NULL
);

CREATE TABLE sorting_item_translations (
    item_id BIGINT NOT NULL REFERENCES sorting_items(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    text TEXT,
    PRIMARY KEY (item_id, language_code)
);

-- Пары для игры "Matching"
CREATE TABLE matching_pairs (
    id BIGSERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    item1_image_url TEXT,
    item1_blur_hash TEXT,
    item2_image_url TEXT,
    item2_blur_hash TEXT,
    pair_order INT NOT NULL
);

CREATE TABLE matching_pair_translations (
    pair_id BIGINT NOT NULL REFERENCES matching_pairs(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    item1_text TEXT,
    item2_text TEXT,
    PRIMARY KEY (pair_id, language_code)
);

-- Элементы для игры "Fill The Blank"
CREATE TABLE fill_the_blank_items (
    id BIGSERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    item_order INT NOT NULL,
    options JSONB -- Опциональный массив вариантов ответа
);

CREATE TABLE fill_the_blank_item_translations (
    item_id BIGINT NOT NULL REFERENCES fill_the_blank_items(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    sentence_template TEXT NOT NULL, -- 'The capital of France is {blank}.'
    correct_answer TEXT NOT NULL,
    PRIMARY KEY (item_id, language_code)
);

-- Задания и выполнения

-- Задания создаваемые учителями для классов
CREATE TABLE assignments (
    id BIGSERIAL PRIMARY KEY,
    teacher_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
    lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    num_activities INT NOT NULL,
    due_date TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (teacher_id, classroom_id, lesson_id) -- Учитель не может назначить один и тот же урок дважды одному классу
);

-- Переводы для заданий
CREATE TABLE assignment_translations (
    assignment_id BIGINT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    title TEXT, -- Необязательное кастомное название задания.
    description TEXT,
    PRIMARY KEY (assignment_id, language_code)
);

-- Записи о выполнении студентами конкретных активностей
CREATE TABLE completions (
    id BIGSERIAL PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    activity_id BIGINT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    assignment_id BIGINT REFERENCES assignments(id) ON DELETE SET NULL, -- Задание может быть удалено, но выполнение останется
    content_type TEXT NOT NULL, -- 'score', 'image_paths', 'text_response'
    content_value JSONB NOT NULL, -- JSONB т.к. может хранить как простые значения, так и массивы (пути к S3 если челик загрузит фото там и т.д)
    time_spent_seconds INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (student_id, activity_id) -- Студент может выполнить одну активность только один раз
);

-- Система значков (Badges)

-- Справочник всех возможных значков в системе
CREATE TABLE badges (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE, -- 'first_completion', 'perfect_score'
    icon_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Переводы для названий и описаний значков
CREATE TABLE badge_translations (
    badge_id BIGINT NOT NULL REFERENCES badges(id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL REFERENCES languages(code),
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    PRIMARY KEY (badge_id, language_code)
);

-- Записи о получении значков пользователями
CREATE TABLE user_badges (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    badge_id BIGINT NOT NULL REFERENCES badges(id) ON DELETE CASCADE,
    earned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, badge_id)
);

-- Автоматизация и Индексы

-- Функция-триггер для автоматического обновления поля updated_at
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Применение триггера ко всем таблицам с полем updated_at
CREATE TRIGGER set_timestamp
BEFORE UPDATE ON "user"
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON classrooms
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON chapters
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON lessons
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON activities
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON assignments
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON completions
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

ALTER TABLE "user" ADD CONSTRAINT email_check CHECK (email ~* '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$');
ALTER TABLE "user" ADD CONSTRAINT experience_points_check CHECK (experience_points >= 0);
ALTER TABLE classrooms ADD CONSTRAINT code_format_check CHECK (code ~* '^[A-Z0-9]{6,8}$');

-- Индексы для ускорения часто используемых запросов
CREATE INDEX idx_users_email ON "user"(email);
CREATE INDEX idx_classrooms_code ON classrooms(code);
CREATE INDEX idx_completions_student_activity ON completions(student_id, activity_id);
CREATE INDEX idx_assignments_classroom ON assignments(classroom_id);

-- Заполнение справочных таблиц начальными данными
INSERT INTO role (code, name) VALUES
    ('student', 'Student'),
    ('teacher', 'Teacher'),
    ('admin', 'Administrator')
ON CONFLICT (code) DO NOTHING;

INSERT INTO languages (code, name, display_order) VALUES
    ('en', 'English', 1),
    ('kk', 'Kazakh', 2),
    ('ru', 'Russian', 3)
ON CONFLICT (code) DO NOTHING;

INSERT INTO grade_levels (name, display_order, is_active) VALUES
    ('Grade 2', 2, true),
    ('Grade 3', 3, true),
    ('Grade 4', 4, true),
    ('Grade 5', 5, true);

-- Переводы для grade levels
INSERT INTO grade_level_translations (grade_level_id, language_code, name) VALUES
    (1, 'en', 'Grade 2'),
    (1, 'kk', '2-сынып'),
    (1, 'ru', '2 класс'),
    (2, 'en', 'Grade 3'),
    (2, 'kk', '3-сынып'),
    (2, 'ru', '3 класс'),
    (3, 'en', 'Grade 4'),
    (3, 'kk', '4-сынып'),
    (3, 'ru', '4 класс'),
    (4, 'en', 'Grade 5'),
    (4, 'kk', '5-сынып'),
    (4, 'ru', '5 класс');

COMMIT;